CREATE DATABASE IF NOT EXISTS hackathon
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'hackathon_user'@'%'
  IDENTIFIED BY 'CHANGE_THIS_PASSWORD';

GRANT ALL PRIVILEGES ON hackathon.* TO 'hackathon_user'@'%';

FLUSH PRIVILEGES;
